# Generated by Django 5.0.6 on 2024-06-27 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbklima", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="localization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dbklima.localization",
                verbose_name="Lokalizace",
            ),
        ),
        migrations.CreateModel(
            name="SubGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subgroup_name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Pojmenování podskupiny",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Kód opatření"
                    ),
                ),
                (
                    "abstract",
                    models.CharField(max_length=255, verbose_name="Shrnutí opatření"),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Podrobný popis opatření"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dbklima.group",
                        verbose_name="Skupina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Podskupina",
                "verbose_name_plural": "Podskupiny",
            },
        ),
    ]
