# Generated by Django 5.0.6 on 2024-06-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbklima", "0002_alter_group_localization_subgroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subgroup",
            name="subgroup_name",
            field=models.CharField(
                max_length=100, verbose_name="Pojmenování podskupiny"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subgroup",
            unique_together={("group", "subgroup_name")},
        ),
    ]
