# Generated by Django 5.0.6 on 2024-06-27 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dbklima", "0003_alter_subgroup_subgroup_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="group",
            unique_together={("localization", "group_name")},
        ),
    ]
