# Generated by Django 5.0.7 on 2024-08-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbklima", "0007_choicename_choice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="choice",
            options={
                "ordering": ["choice_name", "order"],
                "verbose_name": "Volba",
                "verbose_name_plural": "Volby",
            },
        ),
        migrations.AlterField(
            model_name="choice",
            name="order",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Pořadí"),
        ),
    ]
