# Generated by Django 5.0.7 on 2024-08-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbklima", "0009_subgroup_mix_localization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Popis"),
        ),
    ]
