# Generated by Django 5.0.7 on 2024-08-02 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbklima", "0010_alter_choice_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="subgroup",
            name="env",
            field=models.ForeignKey(
                default=1,
                limit_choices_to={"choice_name_id": 1},
                on_delete=django.db.models.deletion.CASCADE,
                to="dbklima.choice",
                verbose_name="Složka životního prostředí",
            ),
            preserve_default=False,
        ),
    ]
