# Generated by Django 5.0.6 on 2024-09-13 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbklima", "0013_alter_subgroup_env_alter_subgroup_env_secondary"),
    ]

    operations = [
        migrations.AddField(
            model_name="subgroup",
            name="conditions_for_implementation",
            field=models.TextField(null=True, verbose_name="Podmínky implementace"),
        ),
        migrations.AddField(
            model_name="subgroup",
            name="difficulty_of_implementation",
            field=models.ForeignKey(
                limit_choices_to={"choice_name_id": 4},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="difficulty_of_implementations",
                to="dbklima.choice",
                verbose_name="Náročnost realizace",
            ),
        ),
        migrations.AddField(
            model_name="subgroup",
            name="potential",
            field=models.ForeignKey(
                limit_choices_to={"choice_name_id": 2},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="potentials",
                to="dbklima.choice",
                verbose_name="Potenciál aplikace",
            ),
        ),
        migrations.AddField(
            model_name="subgroup",
            name="size",
            field=models.ForeignKey(
                limit_choices_to={"choice_name_id": 3},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sizes",
                to="dbklima.choice",
                verbose_name="Rozsah / velikost",
            ),
        ),
    ]
