# Generated by Django 5.0.6 on 2024-09-13 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbklima", "0014_subgroup_conditions_for_implementation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subgroup",
            name="quantification",
            field=models.ForeignKey(
                limit_choices_to={"choice_name_id": 5},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quantifications",
                to="dbklima.choice",
                verbose_name="Kvantifikace dopadu",
            ),
        ),
        migrations.AddField(
            model_name="subgroup",
            name="time_horizon",
            field=models.ForeignKey(
                limit_choices_to={"choice_name_id": 6},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_horizons",
                to="dbklima.choice",
                verbose_name="Časový horizont dopadu",
            ),
        ),
    ]
