# Generated by Django 5.0.6 on 2024-09-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbklima", "0015_subgroup_quantification_subgroup_time_horizon"),
    ]

    operations = [
        migrations.AddField(
            model_name="subgroup",
            name="related",
            field=models.ManyToManyField(blank=True, null=True, to="dbklima.subgroup"),
        ),
    ]
