# Generated by Django 5.0.6 on 2024-09-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbklima", "0016_subgroup_related"),
    ]

    operations = [
        migrations.AddField(
            model_name="subgroup",
            name="conflict",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"choice_name_id": 7},
                related_name="conflicts",
                to="dbklima.choice",
                verbose_name="Střet",
            ),
        ),
        migrations.AddField(
            model_name="subgroup",
            name="other_conflict",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Jiné střety"
            ),
        ),
        migrations.AlterField(
            model_name="subgroup",
            name="related",
            field=models.ManyToManyField(
                blank=True, to="dbklima.subgroup", verbose_name="Návaznost"
            ),
        ),
    ]
