# Generated by Django 5.0.7 on 2024-09-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbklima", "0017_subgroup_conflict_subgroup_other_conflict_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=50, verbose_name="Tag")),
            ],
            options={
                "verbose_name": "TAG",
                "verbose_name_plural": "TAG",
            },
        ),
    ]
