# Generated by Django 5.0.7 on 2024-09-27 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbklima", "0018_tag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={
                "verbose_name": "Kategorie dopadu změny klimatu",
                "verbose_name_plural": "Kategorie dopadu změny klimatu",
            },
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag_name",
            field=models.CharField(max_length=50, verbose_name="Kategorie"),
        ),
        migrations.CreateModel(
            name="TagDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag_detail",
                    models.CharField(max_length=100, verbose_name="Specifický dopad"),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dbklima.tag",
                        verbose_name="Kategorie dopadu změny klimatu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategorie dopadu změny klimatu (Specifický dopad)",
                "verbose_name_plural": "Kategorie dopadu změny klimatu (Specifické dopady)",
            },
        ),
    ]
