# Generated by Django 5.0.7 on 2024-09-27 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbklima", "0019_alter_tag_options_alter_tag_tag_name_tagdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="subgroup",
            name="tag",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dbklima.tagdetail",
                verbose_name="Kategorie dopadu změny klimatu",
            ),
        ),
    ]
