# Generated by Django 5.0.7 on 2024-09-27 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbklima", "0020_subgroup_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="subgroup",
            name="price",
            field=models.PositiveIntegerField(default=0, verbose_name="Hodnota"),
        ),
        migrations.AddField(
            model_name="subgroup",
            name="sdg",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"choice_name_id": 10},
                related_name="sdgs",
                to="dbklima.choice",
                verbose_name="Cíle udržitelného rozvoje (SDG)",
            ),
        ),
        migrations.AlterField(
            model_name="subgroup",
            name="quantification",
            field=models.ForeignKey(
                limit_choices_to={"choice_name_id": 11},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="units",
                to="dbklima.choice",
                verbose_name="Jednotka",
            ),
        ),
    ]
