# Generated by Django 5.0.7 on 2024-09-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbklima", "0022_subgroup_unit_alter_subgroup_quantification"),
    ]

    operations = [
        migrations.AddField(
            model_name="subgroup",
            name="comment",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Komentář"
            ),
        ),
    ]
