# Generated by Django 5.0.7 on 2024-09-27 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbklima", "0023_subgroup_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Example",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "example_name",
                    models.CharField(max_length=100, verbose_name="Název"),
                ),
                ("description", models.TextField(verbose_name="Popis")),
                ("web", models.URLField(verbose_name="Odkaz na www")),
                (
                    "location",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "v ČR"),
                            (2, "v zahraničí"),
                            (3, "v rámci DIVILAND"),
                        ]
                    ),
                ),
                (
                    "subgroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dbklima.subgroup",
                        verbose_name="Podskupina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Realizováno (příklad)",
                "verbose_name_plural": "Realizováno (příklady)",
            },
        ),
    ]
