# Generated by Django 5.0.7 on 2024-09-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbklima", "0024_example"),
    ]

    operations = [
        migrations.AlterField(
            model_name="example",
            name="location",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "v ČR"), (2, "v zahraničí"), (3, "v rámci DIVILAND")],
                verbose_name="Lokace",
            ),
        ),
    ]
