# Generated by Django 5.1.5 on 2025-03-03 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbklima", "0026_subgroup_env_desc_subgroup_tag_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="subgroup",
            name="other_tags",
            field=models.ManyToManyField(
                related_name="other_tags",
                to="dbklima.tagdetail",
                verbose_name="Vedlejší kategorie dopadu změny klimatu",
            ),
        ),
        migrations.AlterField(
            model_name="subgroup",
            name="tag",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="dbklima.tagdetail",
                verbose_name="Kategorie dopadu změny klimatu",
            ),
        ),
    ]
